In [1]:
import numpy as np
import pandas as pd
from pandas import Series as s, DataFrame as df

In [2]:
df1 = pd.read_csv('data/bikes.csv')

In [3]:
df1

,Date,Unnamed: 1,Berri1,Boyer,BrÃ©beuf,CSC (CÃ´te Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,PierDup,Pont_Jacques_Cartier,Rachel / HÃ´tel de Ville,Rachel / Papineau,RenÃ©-LÃ©vesque,Saint-Antoine,Saint-Urbain,Totem_Laurier,University,Viger
0,01/01/2016,00:00,32,0,27,0.0,51.0,16,1,5,1,13,NaN,93,12,6,38,68,14,11
1,02/01/2016,00:00,68,0,6,0.0,93.0,25,2,16,6,9,NaN,141,16,11,67,106,30,14
2,03/01/2016,00:00,78,3,4,0.0,118.0,38,0,6,1,6,NaN,116,25,10,21,59,25,5
3,04/01/2016,00:00,118,6,60,2.0,165.0,80,0,46,0,3,NaN,202,49,9,4,99,111,29
4,05/01/2016,00:00,183,2,25,2.0,239.0,86,2,110,5,3,NaN,241,77,12,11,106,158,44
5,06/01/2016,00:00,305,3,14,45.0,378.0,116,11,126,3,3,NaN,302,120,53,29,189,224,62
6,07/01/2016,00:00,425,0,10,70.0,486.0,142,13,164,5,3,NaN,424,155,60,34,54,313,73
7,08/01/2016,00:00,393,1,14,77.0,439.0,138,10,131,3,18,NaN,432,157,61,75,91,310,66
8,09/01/2016,00:00,139,7,4,34.0,197.0,73,0,42,8,3,NaN,276,38,22,78,114,100,19
9,10/01/2016,00:00,136,30,11,59.0,151.0,46,12,55,10,6,NaN,252,42,13,80,196,73,9
10,11/01/2016,00:00,393,31,28,93.0,508.0,168,12,222,6,17,NaN,439,133,56,193,312,340,60
11,12/01/2016,00:00,398,12,21,129.0,451.0,152,18,206,8,20,NaN,422,139,46,125,253,286,73
12,13/01/2016,00:00,324,0,15,72.0,384.0,126,1,227,6,9,NaN,371,112,31,6,118,234,46
13,14/01/2016,00:00,347,1,2,76.0,437.0,134,16,142,8,9,NaN,390,106,29,1,124,274,45
14,15/01/2016,00:00,367,0,1,70.0,372.0,120,18,115,1,20,NaN,358,123,41,3,66,221,56
15,16/01/2016,00:00,113,0,5,20.0,145.0,42,6,29,7,14,NaN,227,32,12,2,88,70,11
16,17/01/2016,00:00,111,0,8,13.0,118.0,31,3,28,4,8,NaN,189,35,6,4,63,65,10
17,18/01/2016,00:00,340,0,2,72.0,339.0,111,11,99,1,12,NaN,350,105,22,1,235,151,38
18,19/01/2016,00:00,271,0,4,28.0,309.0,121,19,112,2,8,NaN,268,83,10,0,138,153,42
19,20/01/2016,00:00,376,0,12,83.0,432.0,139,31,139,0,7,NaN,415,110,63,119,222,232,76
20,21/01/2016,00:00,450,4,11,75.0,456.0,155,42,163,0,14,NaN,388,133,66,112,293,281,46
21,22/01/2016,00:00,400,5,55,78.0,415.0,155,26,185,0,23,NaN,465,147,75,117,299,230,49
22,23/01/2016,00:00,146,3,12,25.0,162.0,48,11,55,0,11,NaN,237,40,13,62,160,70,15
23,24/01/2016,00:00,116,4,18,27.0,145.0,41,6,57,0,3,NaN,213,43,7,67,155,58,18
24,25/01/2016,00:00,441,2,6,164.0,528.0,168,35,287,4,11,NaN,510,157,61,183,394,354,48
25,26/01/2016,00:00,417,15,7,109.0,543.0,174,42,257,4,15,NaN,421,153,44,166,303,311,64
26,27/01/2016,00:00,460,25,19,143.0,563.0,185,41,272,4,27,NaN,294,192,76,221,393,341,81
27,28/01/2016,00:00,419,22,15,132.0,582.0,181,35,263,9,27,NaN,386,170,80,269,388,396,53
28,29/01/2016,00:00,421,16,27,140.0,523.0,158,35,264,11,25,NaN,435,153,62,195,368,312,58
29,30/01/2016,00:00,136,6,9,35.0,212.0,56,15,76,11,11,NaN,245,52,6,106,160,119,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,02/12/2016,00:00,993,597,130,669.0,NaN,441,262,934,72,348,NaN,1206,651,139,532,1089,664,98
337,03/12/2016,00:00,579,439,101,234.0,NaN,205,106,364,37,189,NaN,763,583,47,267,668,300,26
338,04/12/2016,00:00,646,498,100,303.0,NaN,237,139,377,116,289,NaN,881,329,54,267,678,288,43
339,05/12/2016,00:00,546,317,14,304.0,NaN,238,157,385,16,55,NaN,704,224,89,151,416,185,63
340,06/12/2016,00:00,693,377,22,347.0,NaN,233,134,464,12,62,NaN,672,254,81,184,622,245,71
341,07/12/2016,00:00,660,354,9,376.0,NaN,236,173,407,15,36,NaN,799,254,95,282,593,282,76
342,08/12/2016,00:00,836,495,16,471.0,NaN,308,203,541,19,64,NaN,1076,390,114,364,814,444,105
343,09/12/2016,00:00,546,292,15,164.0,NaN,168,83,286,9,45,NaN,633,220,79,234,416,162,58
344,10/12/2016,00:00,275,185,2,63.0,NaN,85,18,142,12,14,NaN,470,69,31,135,387,53,25
345,11/12/2016,00:00,238,207,6,56.0,NaN,97,28,125,15,55,NaN,438,71,26,85,312,38,17
346,12/12/2016,00:00,353,246,10,91.0,NaN,105,59,196,1,19,NaN,498,115,36,12,429,47,19
347,13/12/2016,00:00,561,308,6,66.0,NaN,166,95,267,1,44,NaN,609,225,68,9,434,183,35
348,14/12/2016,00:00,559,283,7,220.0,NaN,175,132,268,14,13,NaN,700,201,69,56,309,199,50
349,15/12/2016,00:00,443,234,11,203.0,NaN,156,88,196,5,17,NaN,543,153,46,38,321,163,43
350,16/12/2016,00:00,271,159,29,127.0,NaN,116,66,138,8,24,NaN,362,123,48,33,315,118,33
351,17/12/2016,00:00,127,97,6,14.0,NaN,42,8,45,4,3,NaN,231,40,11,9,198,29,12
352,18/12/2016,00:00,93,69,2,6.0,NaN,47,22,24,6,16,NaN,200,29,12,6,248,25,6
353,19/12/2016,00:00,384,162,2,53.0,NaN,97,88,169,5,99,NaN,480,107,46,1,222,124,25
354,20/12/2016,00:00,460,160,6,175.0,NaN,146,93,227,4,6,NaN,543,143,72,17,304,189,46
355,21/12/2016,00:00,461,125,6,223.0,NaN,156,127,266,11,114,NaN,669,186,60,36,433,190,64
356,22/12/2016,00:00,427,101,12,180.0,NaN,113,79,204,16,0,NaN,539,167,67,37,348,162,39
357,23/12/2016,00:00,274,87,14,104.0,NaN,122,56,154,14,0,NaN,421,128,33,61,320,134,26
358,24/12/2016,00:00,78,41,3,28.0,NaN,30,13,30,5,0,NaN,185,22,7,13,95,31,4
359,25/12/2016,00:00,44,24,8,2.0,NaN,22,3,11,1,0,NaN,104,11,9,9,63,10,7
360,26/12/2016,00:00,53,14,3,12.0,NaN,37,11,4,2,0,NaN,103,21,7,9,73,17,6
361,27/12/2016,00:00,137,42,1,30.0,NaN,57,26,33,8,0,NaN,205,59,12,5,136,40,11
362,28/12/2016,00:00,181,55,1,70.0,NaN,91,44,68,4,0,NaN,288,85,24,16,171,76,19
363,29/12/2016,00:00,120,33,5,35.0,NaN,46,18,41,8,0,NaN,203,53,13,6,208,38,14
364,30/12/2016,00:00,120,59,13,2.0,NaN,53,29,53,3,10,NaN,72,55,15,0,218,68,3
365,31/12/2016,00:00,52,26,2,135.0,NaN,23,11,12,6,0,NaN,122,16,4,17,102,16,3

In [4]:
df2 = pd.read_csv('data/bikes.csv', header=None)
df2.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,Date,NaN,Berri1,Boyer,BrÃ©beuf,CSC (CÃ´te Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,PierDup,Pont_Jacques_Cartier,Rachel / HÃ´tel de Ville,Rachel / Papineau,RenÃ©-LÃ©vesque,Saint-Antoine,Saint-Urbain,Totem_Laurier,University,Viger
1,01/01/2016,00:00,32,0,27,0,51,16,1,5,1,13,NaN,93,12,6,38,68,14,11
2,02/01/2016,00:00,68,0,6,0,93,25,2,16,6,9,NaN,141,16,11,67,106,30,14
3,03/01/2016,00:00,78,3,4,0,118,38,0,6,1,6,NaN,116,25,10,21,59,25,5
4,04/01/2016,00:00,118,6,60,2,165,80,0,46,0,3,NaN,202,49,9,4,99,111,29

In [5]:
df3 = pd.read_table('data/bikes.csv', sep=',', header=None)

In [6]:
df3

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,Date,NaN,Berri1,Boyer,BrÃ©beuf,CSC (CÃ´te Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,PierDup,Pont_Jacques_Cartier,Rachel / HÃ´tel de Ville,Rachel / Papineau,RenÃ©-LÃ©vesque,Saint-Antoine,Saint-Urbain,Totem_Laurier,University,Viger
1,01/01/2016,00:00,32,0,27,0,51,16,1,5,1,13,NaN,93,12,6,38,68,14,11
2,02/01/2016,00:00,68,0,6,0,93,25,2,16,6,9,NaN,141,16,11,67,106,30,14
3,03/01/2016,00:00,78,3,4,0,118,38,0,6,1,6,NaN,116,25,10,21,59,25,5
4,04/01/2016,00:00,118,6,60,2,165,80,0,46,0,3,NaN,202,49,9,4,99,111,29
5,05/01/2016,00:00,183,2,25,2,239,86,2,110,5,3,NaN,241,77,12,11,106,158,44
6,06/01/2016,00:00,305,3,14,45,378,116,11,126,3,3,NaN,302,120,53,29,189,224,62
7,07/01/2016,00:00,425,0,10,70,486,142,13,164,5,3,NaN,424,155,60,34,54,313,73
8,08/01/2016,00:00,393,1,14,77,439,138,10,131,3,18,NaN,432,157,61,75,91,310,66
9,09/01/2016,00:00,139,7,4,34,197,73,0,42,8,3,NaN,276,38,22,78,114,100,19
10,10/01/2016,00:00,136,30,11,59,151,46,12,55,10,6,NaN,252,42,13,80,196,73,9
11,11/01/2016,00:00,393,31,28,93,508,168,12,222,6,17,NaN,439,133,56,193,312,340,60
12,12/01/2016,00:00,398,12,21,129,451,152,18,206,8,20,NaN,422,139,46,125,253,286,73
13,13/01/2016,00:00,324,0,15,72,384,126,1,227,6,9,NaN,371,112,31,6,118,234,46
14,14/01/2016,00:00,347,1,2,76,437,134,16,142,8,9,NaN,390,106,29,1,124,274,45
15,15/01/2016,00:00,367,0,1,70,372,120,18,115,1,20,NaN,358,123,41,3,66,221,56
16,16/01/2016,00:00,113,0,5,20,145,42,6,29,7,14,NaN,227,32,12,2,88,70,11
17,17/01/2016,00:00,111,0,8,13,118,31,3,28,4,8,NaN,189,35,6,4,63,65,10
18,18/01/2016,00:00,340,0,2,72,339,111,11,99,1,12,NaN,350,105,22,1,235,151,38
19,19/01/2016,00:00,271,0,4,28,309,121,19,112,2,8,NaN,268,83,10,0,138,153,42
20,20/01/2016,00:00,376,0,12,83,432,139,31,139,0,7,NaN,415,110,63,119,222,232,76
21,21/01/2016,00:00,450,4,11,75,456,155,42,163,0,14,NaN,388,133,66,112,293,281,46
22,22/01/2016,00:00,400,5,55,78,415,155,26,185,0,23,NaN,465,147,75,117,299,230,49
23,23/01/2016,00:00,146,3,12,25,162,48,11,55,0,11,NaN,237,40,13,62,160,70,15
24,24/01/2016,00:00,116,4,18,27,145,41,6,57,0,3,NaN,213,43,7,67,155,58,18
25,25/01/2016,00:00,441,2,6,164,528,168,35,287,4,11,NaN,510,157,61,183,394,354,48
26,26/01/2016,00:00,417,15,7,109,543,174,42,257,4,15,NaN,421,153,44,166,303,311,64
27,27/01/2016,00:00,460,25,19,143,563,185,41,272,4,27,NaN,294,192,76,221,393,341,81
28,28/01/2016,00:00,419,22,15,132,582,181,35,263,9,27,NaN,386,170,80,269,388,396,53
29,29/01/2016,00:00,421,16,27,140,523,158,35,264,11,25,NaN,435,153,62,195,368,312,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
337,02/12/2016,00:00,993,597,130,669,NaN,441,262,934,72,348,NaN,1206,651,139,532,1089,664,98
338,03/12/2016,00:00,579,439,101,234,NaN,205,106,364,37,189,NaN,763,583,47,267,668,300,26
339,04/12/2016,00:00,646,498,100,303,NaN,237,139,377,116,289,NaN,881,329,54,267,678,288,43
340,05/12/2016,00:00,546,317,14,304,NaN,238,157,385,16,55,NaN,704,224,89,151,416,185,63
341,06/12/2016,00:00,693,377,22,347,NaN,233,134,464,12,62,NaN,672,254,81,184,622,245,71
342,07/12/2016,00:00,660,354,9,376,NaN,236,173,407,15,36,NaN,799,254,95,282,593,282,76
343,08/12/2016,00:00,836,495,16,471,NaN,308,203,541,19,64,NaN,1076,390,114,364,814,444,105
344,09/12/2016,00:00,546,292,15,164,NaN,168,83,286,9,45,NaN,633,220,79,234,416,162,58
345,10/12/2016,00:00,275,185,2,63,NaN,85,18,142,12,14,NaN,470,69,31,135,387,53,25
346,11/12/2016,00:00,238,207,6,56,NaN,97,28,125,15,55,NaN,438,71,26,85,312,38,17
347,12/12/2016,00:00,353,246,10,91,NaN,105,59,196,1,19,NaN,498,115,36,12,429,47,19
348,13/12/2016,00:00,561,308,6,66,NaN,166,95,267,1,44,NaN,609,225,68,9,434,183,35
349,14/12/2016,00:00,559,283,7,220,NaN,175,132,268,14,13,NaN,700,201,69,56,309,199,50
350,15/12/2016,00:00,443,234,11,203,NaN,156,88,196,5,17,NaN,543,153,46,38,321,163,43
351,16/12/2016,00:00,271,159,29,127,NaN,116,66,138,8,24,NaN,362,123,48,33,315,118,33
352,17/12/2016,00:00,127,97,6,14,NaN,42,8,45,4,3,NaN,231,40,11,9,198,29,12
353,18/12/2016,00:00,93,69,2,6,NaN,47,22,24,6,16,NaN,200,29,12,6,248,25,6
354,19/12/2016,00:00,384,162,2,53,NaN,97,88,169,5,99,NaN,480,107,46,1,222,124,25
355,20/12/2016,00:00,460,160,6,175,NaN,146,93,227,4,6,NaN,543,143,72,17,304,189,46
356,21/12/2016,00:00,461,125,6,223,NaN,156,127,266,11,114,NaN,669,186,60,36,433,190,64
357,22/12/2016,00:00,427,101,12,180,NaN,113,79,204,16,0,NaN,539,167,67,37,348,162,39
358,23/12/2016,00:00,274,87,14,104,NaN,122,56,154,14,0,NaN,421,128,33,61,320,134,26
359,24/12/2016,00:00,78,41,3,28,NaN,30,13,30,5,0,NaN,185,22,7,13,95,31,4
360,25/12/2016,00:00,44,24,8,2,NaN,22,3,11,1,0,NaN,104,11,9,9,63,10,7
361,26/12/2016,00:00,53,14,3,12,NaN,37,11,4,2,0,NaN,103,21,7,9,73,17,6
362,27/12/2016,00:00,137,42,1,30,NaN,57,26,33,8,0,NaN,205,59,12,5,136,40,11
363,28/12/2016,00:00,181,55,1,70,NaN,91,44,68,4,0,NaN,288,85,24,16,171,76,19
364,29/12/2016,00:00,120,33,5,35,NaN,46,18,41,8,0,NaN,203,53,13,6,208,38,14
365,30/12/2016,00:00,120,59,13,2,NaN,53,29,53,3,10,NaN,72,55,15,0,218,68,3
366,31/12/2016,00:00,52,26,2,135,NaN,23,11,12,6,0,NaN,122,16,4,17,102,16,3

In [7]:
df4 = pd.read_csv('data/bikes.csv', nrows=5)
df4

,Date,Unnamed: 1,Berri1,Boyer,BrÃ©beuf,CSC (CÃ´te Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,PierDup,Pont_Jacques_Cartier,Rachel / HÃ´tel de Ville,Rachel / Papineau,RenÃ©-LÃ©vesque,Saint-Antoine,Saint-Urbain,Totem_Laurier,University,Viger
0,01/01/2016,00:00,32,0,27,0,51,16,1,5,1,13,NaN,93,12,6,38,68,14,11
1,02/01/2016,00:00,68,0,6,0,93,25,2,16,6,9,NaN,141,16,11,67,106,30,14
2,03/01/2016,00:00,78,3,4,0,118,38,0,6,1,6,NaN,116,25,10,21,59,25,5
3,04/01/2016,00:00,118,6,60,2,165,80,0,46,0,3,NaN,202,49,9,4,99,111,29
4,05/01/2016,00:00,183,2,25,2,239,86,2,110,5,3,NaN,241,77,12,11,106,158,44

In [8]:
import sys

In [9]:
df4.to_csv(sys.stdout)

,Date,Unnamed: 1,Berri1,Boyer,BrÃ©beuf,CSC (CÃ´te Sainte-Catherine),Maisonneuve_2,Maisonneuve_3,Notre-Dame,Parc,PierDup,Pont_Jacques_Cartier,Rachel / HÃ´tel de Ville,Rachel / Papineau,RenÃ©-LÃ©vesque,Saint-Antoine,Saint-Urbain,Totem_Laurier,University,Viger
0,01/01/2016,00:00,32,0,27,0,51,16,1,5,1,13,,93,12,6,38,68,14,11
1,02/01/2016,00:00,68,0,6,0,93,25,2,16,6,9,,141,16,11,67,106,30,14
2,03/01/2016,00:00,78,3,4,0,118,38,0,6,1,6,,116,25,10,21,59,25,5
3,04/01/2016,00:00,118,6,60,2,165,80,0,46,0,3,,202,49,9,4,99,111,29
4,05/01/2016,00:00,183,2,25,2,239,86,2,110,5,3,,241,77,12,11,106,158,44

In [10]:
df4.to_csv(sys.stdout, sep='#')

#Date#Unnamed: 1#Berri1#Boyer#BrÃ©beuf#CSC (CÃ´te Sainte-Catherine)#Maisonneuve_2#Maisonneuve_3#Notre-Dame#Parc#PierDup#Pont_Jacques_Cartier#Rachel / HÃ´tel de Ville#Rachel / Papineau#RenÃ©-LÃ©vesque#Saint-Antoine#Saint-Urbain#Totem_Laurier#University#Viger
0#01/01/2016#00:00#32#0#27#0#51#16#1#5#1#13##93#12#6#38#68#14#11
1#02/01/2016#00:00#68#0#6#0#93#25#2#16#6#9##141#16#11#67#106#30#14
2#03/01/2016#00:00#78#3#4#0#118#38#0#6#1#6##116#25#10#21#59#25#5
3#04/01/2016#00:00#118#6#60#2#165#80#0#46#0#3##202#49#9#4#99#111#29
4#05/01/2016#00:00#183#2#25#2#239#86#2#110#5#3##241#77#12#11#106#158#44

In [15]:
df4.to_csv(sys.stdout, sep='#', columns=['Date', 'Berry1'])

#Date#Berry1
0#01/01/2016#
1#02/01/2016#
2#03/01/2016#
3#04/01/2016#
4#05/01/2016#